#!/usr/bin/env bash
# Build a single self-contained .shen for Bifrost --shake / single-file yggdrasil.
# Order: pure oracle → portable API → smoke body.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/programs/sha256-smoke.shake.shen}"
{
  echo '\\ AUTO-GENERATED by scripts/bundle-shake-entry.sh — do not edit.'
  echo '\\ Pure-path only (no host). For Bifrost --shake and yggdrasil single-file.'
  echo
  cat "$ROOT/shen/x/sha256-pure.shen"
  echo
  cat "$ROOT/shen/x/sha256-portable.shen"
  echo
  cat "$ROOT/programs/sha256-smoke-body.shen"
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
